### ISSUE TITLE
cargo test / cargo build fail on mbedtls-sys-auto v2.18.1 (Ubuntu)

### ISSUE THREAD

**Issue by jonathonfletcher** [mobilecoinofficial/mobilecoin#167]
Hi,

I'm on commit b3ef5e64eb476c02867b48c7d0ac613a7f1d9a68 with a clean repo. After ```mob prompt``` I find both ```cargo build``` and ```cargo test``` fail on mbedtls-sys-auto v2.18.1 (https://github.com/mobilecoinofficial/rust-mbedtls.git?tag=mc-0.2#20e6fbb6).

Output shown below. The error triggering the failure is

```sh
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_CXX_COMPILER
    CMAKE_CXX_FLAGS


vendor/include/mbedtls/bignum.h:140:49: warning: declaration does not declare anything [-Wmissing-declarations], err: false
```

How can I resolve this?

```sh
error: failed to run custom build command for `mbedtls-sys-auto v2.18.1 (https://github.com/mobilecoinofficial/rust-mbedtls.git?tag=mc-0.2#20e6fbb6)`

Caused by:
  process didn't exit successfully: `/tmp/mobilenode/target/debug/build/mbedtls-sys-auto-40eeaf3323369c4e/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=RUST_MBEDTLS_SYS_SOURCE
```
[.. omitted ..]
```sh
running: "cmake" "cmake" "/tmp/mobilenode/cargo/git/checkouts/rust-mbedtls-7d1033e9d0cc8048/20e6fbb/mbedtls-sys/vendor" "-DENABLE_PROGRAMS=OFF" "-DENABLE_TESTING=OFF" "-DCMAKE_INSTALL_PREFIX=/tmp/mobilenode/target/debug/build/mbedtls-sys-auto-ce8c8c66c68d9b4d/out" "-DCMAKE_C_FLAGS= -DMBEDTLS_CONFIG_FILE=\"\\\"/tmp/mobilenode/target/debug/build/mbedtls-sys-auto-ce8c8c66c68d9b4d/out/config.h\\\"\" -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
-- Found Perl: /usr/bin/perl (found version "5.26.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/mobilenode/target/debug/build/mbedtls-sys-auto-ce8c8c66c68d9b4d/out/build
running: "cmake" "cmake" "--build" "." "--target" "lib" "--config" "Debug" "--"
Scanning dependencies of target mbedcrypto
[100%] Linking C static library libmbedtls.a
[100%] Built target mbedtls
Scanning dependencies of target lib
[100%] Built target lib
cargo:root=/tmp/mobilenode/target/debug/build/mbedtls-sys-auto-ce8c8c66c68d9b4d/out
cargo:rustc-link-search=native=/tmp/mobilenode/target/debug/build/mbedtls-sys-auto-ce8c8c66c68d9b4d/out/build/library
running: "cmake" "cmake" "/tmp/mobilenode/cargo/git/checkouts/rust-mbedtls-7d1033e9d0cc8048/20e6fbb/mbedtls-sys/vendor" "-DENABLE_PROGRAMS=OFF" "-DENABLE_TESTING=OFF" "-DCMAKE_INSTALL_PREFIX=/tmp/mobilenode/target/debug/build/mbedtls-sys-auto-ce8c8c66c68d9b4d/out" "-DCMAKE_C_FLAGS= -DMBEDTLS_CONFIG_FILE=\"\\\"/tmp/mobilenode/target/debug/build/mbedtls-sys-auto-ce8c8c66c68d9b4d/out/config.h\\\"\" -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/mobilenode/target/debug/build/mbedtls-sys-auto-ce8c8c66c68d9b4d/out/build
running: "cmake" "cmake" "--build" "." "--target" "lib" "--config" "Debug" "--"
[100%] Built target mbedtls
[100%] Built target lib
cargo:root=/tmp/mobilenode/target/debug/build/mbedtls-sys-auto-ce8c8c66c68d9b4d/out
cargo:rustc-link-search=native=/tmp/mobilenode/target/debug/build/mbedtls-sys-auto-ce8c8c66c68d9b4d/out/build/crypto/library
cargo:rustc-link-lib=mbedtls
cargo:rustc-link-lib=mbedx509
cargo:rustc-link-lib=mbedcrypto

--- stderr
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_CXX_COMPILER
    CMAKE_CXX_FLAGS


vendor/include/mbedtls/bignum.h:140:49: warning: declaration does not declare anything [-Wmissing-declarations], err: false
thread 'main' panicked at 'capacity overflow', src/liballoc/raw_vec.rs:777:5
stack backtrace:
   0:     0x55a0ecf3ecf4 - backtrace::backtrace::libunwind::trace::h0a48c85c8012426b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55a0ecf3ecf4 - backtrace::backtrace::trace_unsynchronized::hd59d821c5709c879
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55a0ecf3ecf4 - std::sys_common::backtrace::_print_fmt::h1aa050417bb0b607
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x55a0ecf3ecf4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h068618ade673b259
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x55a0ecf64bfc - core::fmt::write::h72d2c3a2a8405f91
                               at src/libcore/fmt/mod.rs:1025
   5:     0x55a0ecf3b037 - std::io::Write::write_fmt::h36b1a7b93b325264
                               at src/libstd/io/mod.rs:1426
   6:     0x55a0ecf4185e - std::sys_common::backtrace::_print::h40b9c256f1edfa08
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x55a0ecf4185e - std::sys_common::backtrace::print::h0f6ce4b3cbaba788
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x55a0ecf4185e - std::panicking::default_hook::{{closure}}::h2e0a4a0d4aa5cb77
                               at src/libstd/panicking.rs:193
   9:     0x55a0ecf41551 - std::panicking::default_hook::ha8ece3680c7da126
                               at src/libstd/panicking.rs:210
  10:     0x55a0ecf42010 - std::panicking::rust_panic_with_hook::h748222843c9136a2
                               at src/libstd/panicking.rs:475
  11:     0x55a0ecf41aee - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x55a0ecf615ce - core::panicking::panic_fmt::h28daaedf5bd7eef6
                               at src/libcore/panicking.rs:84
  13:     0x55a0ecf6151a - core::panicking::panic::h808e87b2d4de672e
                               at src/libcore/panicking.rs:51
  14:     0x55a0ecf5bcaa - alloc::raw_vec::capacity_overflow::h177048cbd6b65c54
                               at src/liballoc/raw_vec.rs:777
  15:     0x55a0eca2075a - alloc::raw_vec::RawVec<T,A>::allocate_in::{{closure}}::h1f024ddffed38acc
                               at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/liballoc/raw_vec.rs:86
  16:     0x55a0ec99129a - core::option::Option<T>::unwrap_or_else::h12700168cffe883c
                               at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/libcore/option.rs:422
  17:     0x55a0eca20232 - alloc::raw_vec::RawVec<T,A>::allocate_in::he94ec6f14f6effba
                               at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/liballoc/raw_vec.rs:86
  18:     0x55a0eca1e8f6 - alloc::raw_vec::RawVec<T>::with_capacity::h9d9a6f8e01d954a4
                               at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/liballoc/raw_vec.rs:167
  19:     0x55a0eca0ca74 - alloc::collections::vec_deque::VecDeque<T>::with_capacity::h82bf8a0195d39c4c
                               at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/liballoc/collections/vec_deque.rs:481
  20:     0x55a0eca0ce03 - alloc::collections::vec_deque::VecDeque<T>::new::h41ecabbd34c43581
                               at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/liballoc/collections/vec_deque.rs:460
  21:     0x55a0ec9bbb13 - <bindgen::ir::enum_ty::Enum as bindgen::codegen::CodeGenerator>::codegen::h65f221873cf84d2d
                               at /tmp/mobilenode/cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.51.1/src/codegen/mod.rs:2733
  22:     0x55a0eca4abad - <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen::hc6c509b6e883ff09
                               at /tmp/mobilenode/cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.51.1/src/codegen/mod.rs:813
  23:     0x55a0eca48a86 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::h36b15e1b2a12bd84
                               at /tmp/mobilenode/cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.51.1/src/codegen/mod.rs:381
  24:     0x55a0ecac4b3c - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}::h6f0a4285a591820e
                               at /tmp/mobilenode/cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.51.1/src/codegen/mod.rs:403
  25:     0x55a0ec966497 - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::h5b2af8b650b98d2a
                               at /tmp/mobilenode/cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.51.1/src/codegen/mod.rs:433
  26:     0x55a0eca489d2 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::h36b15e1b2a12bd84
                               at /tmp/mobilenode/cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.51.1/src/codegen/mod.rs:372
  27:     0x55a0ecad3c53 - bindgen::codegen::codegen::{{closure}}::h9199f1ac2fc654b7
                               at /tmp/mobilenode/cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.51.1/src/codegen/mod.rs:3632
  28:     0x55a0ec978313 - bindgen::ir::context::BindgenContext::gen::h5f0a6988055d593d
                               at /tmp/mobilenode/cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.51.1/src/ir/context.rs:1200
  29:     0x55a0ecad323b - bindgen::codegen::codegen::h2b5265794d50976f
                               at /tmp/mobilenode/cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.51.1/src/codegen/mod.rs:3606
  30:     0x55a0ec9496dc - bindgen::Bindings::generate::h1fcc9e6d0fd7a027
                               at /tmp/mobilenode/cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.51.1/src/lib.rs:1882
  31:     0x55a0ec947477 - bindgen::Builder::generate::hac01f5abdde62d9c
                               at /tmp/mobilenode/cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.51.1/src/lib.rs:1244
  32:     0x55a0ec874fa9 - build_script_build::mod_bindgen::<impl build_script_build::BuildConfig>::bindgen::h6311779a245076fc
                               at /tmp/mobilenode/cargo/git/checkouts/rust-mbedtls-7d1033e9d0cc8048/20e6fbb/mbedtls-sys/build/bindgen.rs:92
  33:     0x55a0ec877f8b - build_script_build::main::hd0167bc603ed6a0d
                               at /tmp/mobilenode/cargo/git/checkouts/rust-mbedtls-7d1033e9d0cc8048/20e6fbb/mbedtls-sys/build/build.rs:109
  34:     0x55a0ec885e40 - std::rt::lang_start::{{closure}}::h5fbcaa54acc38185
                               at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/libstd/rt.rs:67
  35:     0x55a0ecf41983 - std::rt::lang_start_internal::{{closure}}::ha966a90a2223d318
                               at src/libstd/rt.rs:52
  36:     0x55a0ecf41983 - std::panicking::try::do_call::h7048802f1f0056de
                               at src/libstd/panicking.rs:292
  37:     0x55a0ecf49bda - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  38:     0x55a0ecf42490 - std::panicking::try::h3d7ba80ee84a3ede
                               at src/libstd/panicking.rs:270
  39:     0x55a0ecf42490 - std::panic::catch_unwind::h2f15a5533e64a496
                               at src/libstd/panic.rs:394
  40:     0x55a0ecf42490 - std::rt::lang_start_internal::h0e133c31a2e415aa
                               at src/libstd/rt.rs:51
  41:     0x55a0ec885e19 - std::rt::lang_start::h472c3670a0d6a390
                               at /rustc/19bd93467617a447c22ec32cc1cf14d40cb84ccf/src/libstd/rt.rs:67
  42:     0x55a0ec87809a - main
  43:     0x7f53c64a8b97 - __libc_start_main
  44:     0x55a0ec86f1da - _start
  45:                0x0 - <unknown>

root@d5223bf05724:/tmp/mobilenode#
```

**Comment by jonathonfletcher** [comment]
Figured this out:

When building on older hardware, the target-cpu may need changing. Looks like the distribution is set to use target-cpu=skylake. Check this by adding ```-v``` to the ```cargo build``` or ```cargo test``` and looking at the rustc flags.

To work around this (on older hardware), prefix the ```cargo build``` with ```env RUSTFLAGS="-C target-cpu=native"```.

Closing this.
